import Categories from '@/components/categories';
import FeaturedTvSeries from '@/components/featured-tvSeries';
import MoviesSection from '@/components/movies-section';
import { getAllTvSeries, getTvSerieCategories } from '@/services/FetchProcess';
import { randomInt } from 'crypto';
import { Metadata } from 'next';
import React from 'react';

export const metadata: Metadata = {
  title: "Tv Series",
  description: "Generated by create next app",
};

async function Series() {
  const [{results:tvSeries}, {genres:tvSerieCategories}] = await Promise.all([getAllTvSeries(),getTvSerieCategories()]);

  return (
    <div>
      <FeaturedTvSeries tvSeries={tvSeries[randomInt(0,19)]} isCompact={true} />
      <Categories categories={tvSerieCategories} urlParams='tv-series' />
      <MoviesSection title="All TV Series" movies={tvSeries} urlParams='/tv-series/details' />
    </div>
  )
}

export default Series
