import type { Metadata } from "next";
import '@/styles/reset.css';
import "@/styles/globals.css";
import Navbar from "@/components/header";
import Footer from "@/components/footer";
import {Inter} from 'next/font/google'

export const metadata: Metadata = {
  title: "Homepage",
  description: "Generated by create next app",
};

const inter = Inter({subsets:["latin"]});

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={inter.className}>
      <body className="body-container">
        <Navbar/>
        <main>
          {children}
        </main>
        <Footer/>
      </body>
    </html>
  );
}
